# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_id_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('mock_data', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('parent_father', models.CharField(blank=True, max_length=120, null=True)),
                ('parent_mother', models.CharField(blank=True, max_length=120, null=True)),
                ('designation', models.CharField(blank=True, max_length=120, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=120, null=True)),
                ('dob', models.CharField(default=datetime.date.today, max_length=10)),
                ('joining_date', models.CharField(default=datetime.date.today, max_length=10)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(default='media/user_images/icon.png', upload_to='media/user_images/')),
                ('type', models.CharField(choices=[('direct', 'direct'), ('indirect', 'indirect')], default='direct', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employee_id', models.ForeignKey(db_column='employee_id_list.employee_id', on_delete=django.db.models.deletion.CASCADE, to='employee_data.employee_id_list')),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='employeedata',
            name='gender',
            field=models.ForeignKey(db_column='gender.id', on_delete=django.db.models.deletion.CASCADE, to='employee_data.gender'),
        ),
    ]
