# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0002_auto_20180720_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='type',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='direct', max_length=50),
        ),
    ]
