# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0007_auto_20180722_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_id_list',
            name='employee_id',
            field=models.CharField(max_length=120),
        ),
    ]
